Hotfix - 도커파일이 캐시 된줄알았던 이슈 에 대한 해결
themoment-team/HiRecruit-server pull request #275
Opened 2022-08-02 12:03 UTC by codnstj

# 회고
@jyeonjyan @siwony  
## 문제상황
- 도커 캐시적용 및 레디스 서버를 교체한 이후로 서버 로그에서 기존 redis 주소 를 접근하는 이슈가 발생  
#252 
#271
#272 

-> 이 이슈를 Dockerfile 이 캐시 되어 기존의 파일을 접근하는것이라고 생각함 

## 원인
- redis 서버를 기존 ECS 컨테이너 에서 현재 운영중인 EC2 Data-Bridge 로 이전할 당시 Redis 의 주소를 DockerFile 내 ENTRYPOINT 맨 마지막에 redis.host 로 명시함 
- ENTRYPOINT 는 도커 컨테이너를 처음 최초 run 시 실행되는 명령어 이므로 , 이점 때문에 캐시 되었다고 생각을 했었다.
- 하지만 ENTRYPOINT 가 실행되고 난후 서버에서 S3 secrets 버킷에 저장된 .env.prod 가 적용됨

-> 결과적으로 S3 버킷에 있는 .env.prod 의 redis.host 를 바꿔줘야했다. @siwony  멍청아
~난 몰랐지 ! S3 에 저런 환경변수가 있을줄은...~

## 과정
- 처음엔 DockerFile 의 대한 문제를 확인하기 시작함
  - EntryPoint 부분이 캐싱 된다고 생각했다.
  - 수정된 DockerFile 에서 entrypoint.sh 라는 파일을 찾을수 없어서 생기는 일이라고 생각했다.
- 다음엔 워크플로우 의 대한 문제를 확인하게 됨
  - 워크 플로우 내부의 이미지 태그가 모두 Latest 로 통일되어 이미지가 중복이 일어난다.라고 생각이 들었지만 이는 말이 안됬었다.
  - 워크 플로우 의 env 설정이 잘못 되었다 라고 생각했다.
  - 워크 플로우 의 캐싱 부분이 다시 한번 문제가 된다고 생각했다.
  - EntryPoint 를 TaskDefinition Steps 에 넣어주면 되는것이라고 생각했다.
    - 이는 애초에 깃헙 액션에서 지원하지 않았던 커맨드였다.
- 모든 생각을 해봤지만 역시 ECR 과 ECS 서비스 를 삭제후 다시 구성하는것이 좋겠다고 생각했다.
- ECS 서비스를 다시 구성한후 WorkFlow 에서 S3 시크릿에 Redis 관련 변수가 있는지 확인해봤는데 있었다.

## 해결 방안
- 그냥 S3 에 직접 접근해서 기존 .env.prod 파일의 redis 호스트를 바꿔주었다.
- 추가 적으로 기존에 롤백했던 부분을 다시 구성 해줬습니다 이부분은 한번 @jyeonjyan  확인해주세요
- Latest 라는 태그를 모든 이미지로 사용하는 것은 매우 부적절하다는 상현이 형의 조언을 들어 이를 GithubSHA 와 브랜치명으로 이미지 태그를 변경후 TaskDefinition 파일에도 매 워크플로우마다 설정해주도록 설정했습니다.
- 추가적으로 기존 컨테이너의 CPU 및 메모리 자원이 너무많은 여유를 두어 CPU 는 기존 1024 d에서 512 로 메모리는 기존 3072 에서 1024 로 대폭 줄였습니다. 이후에 메모리 사용량을 체크하여 한달정도 서비스를 해보고 이후에 늘릴지를 고민해보겠습니다.

> 앞으론 Redis 호스트가 만일 바뀌게 된다면 S3 의 .prod.env 도 꼭 바꿔주길 바래요 !!

2022-08-02 12:56 UTC, jyeonjyan commented
> -> 결과적으로 S3 버킷에 있는 .env.prod 의 redis.host 를 바꿔줘야했다. @siwony 멍청아
난 몰랐지 ! S3 에 저런 환경변수가 있을줄은...

이건 내가 적용한거긴 해  ㅋㅋㅋㅋㅋㅋ 🥲

2022-08-02 13:07 UTC, jyeonjyan requested changes
항상 오래 쩔쩔매는 이슈는 Back to the basic (근본)에서 문제를 찾아야 하는 것 같아요.
고민했던 부분들도 깔끔히 정리해주시고. 이슈는 현명하게 해결한 것 같아 제가 다 기분이 좋습니다.

코멘트 확인해주세요
수고하셨습니다 :)

2022-08-02 13:07 UTC, jyeonjyan commented on .github/workflows/github-action-prod-cd.yml
> +          cache-to: type=gha,mode=max
`cache-to`, `cache-from` 이 쌍으로 있어야만 최신의 build 정보가 upload, download 되긴하는데.
(결론 caching 을 적용하는데 이 방법이 적절 함)

github action cach-from to는 이번 이슈를 해결하면서 성능(빌드타임) 저하 문제를 야기하는것을 확인해서 운영에서 조금 더 돌려본뒤(실험) 적절한 trade-off 를 해야할 것 같아 리뷰 남겨둡니다.

2022-08-02 13:07 UTC, jyeonjyan commented on .github/workflows/github-action-prod-cd.yml
> +            image: ${{ steps.set-env.outputs.full-image }}
`full-image`가 좋은 변수명인지는 모르겠습니다.
`ex) full-image-path` 등 좀 더 명확한 네이밍을 해보는건 어떤가요?

2022-08-02 13:07 UTC, jyeonjyan commented on task-definition.json
> +  "memory": "1024"
이 크기로 설정한 이유를 알고 싶습니다.!!

2022-08-02 13:07 UTC, jyeonjyan commented on Dockerfile
> +ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/hirecruit-1.0.jar","--spring.profiles.active=prod","--redis.host=10.0.28.60"]
이처럼, Dockerfile이 `entrypoint.sh`를 직접 override 하는게 아니라면..
`entrypoint.sh`는 필요없는 스크립트가 되어 삭제 되어도 되지 않을까요?

2022-08-03 04:37 UTC, siwony approved these changes
LGTM

2022-08-06 07:06 UTC, jyeonjyan commented on task-definition.json
> +  "memory": "1024"
LGTM

2022-08-06 07:07 UTC, jyeonjyan approved these changes
LGTM

2022-08-06 07:08 UTC, merged