Feature/aws sns [create topic 피쳐 개발]
themoment-team/HiRecruit-server pull request #46
Opened 2022-05-21 09:40 UTC by jyeonjyan

## 작업 내용
* create topic 피처 개발

![sns-topic-generated](https://user-images.githubusercontent.com/67095821/169645656-58dedc2a-b97d-46a2-9391-30efb226f9ab.png)

## 부가 설명
topic(주제)의 역할은.. 한마디로 Grouping이다.
회원가입 주제, 멘티로 등록 주제 ... 등등 만들어 해당 주제(카테고리)에 알맞는 sns 를 보낼 수 있게 한다.

1. aws-sns 주제(대분류)를 만들어 
2. 그 주제를 구독할 수 있게 한다. 
3. 그 주제를 구독한 구독자들에게 알림을 보낼 수 있도록 해준다.

![CleanShot 2022-05-21 at 18 22 34@2x](https://user-images.githubusercontent.com/67095821/169645140-1790cc3f-0ce6-4e72-8ce9-1f62ce2571a5.png)

## 리뷰 받고 싶은 부분
최대한 TDD 로 개발하려고 노력했다. 
가급적 private 메소드는 피하고 mocking 하기 쉽게끔 facade-pattern 으로 서브 클라이언트(개발자)가 알 필요 없는 시스템을 숨겼다.

#### <의사결정 주제>
* `SnsTopicSubSystemFacade/servingTopicRequestToSnsClient()` 와 `SnsTopicSubSystemFacade/isSdkHttpResponseHealthy()` 를 합쳐야 할까 ?

`servingTopicRequestToSnsClient()` 메소드가 `isSdkHttpResponseHealthy()` 리턴값에 100% 의존하고 있어 합쳐도 될 것 같다는 생각도 들지만. 나중에 HttpResponse 의 결과 값을 mocking(조작) 하기 위해서는 분리하는것도 좋다는 생각이 든다.

#### <현재>
두 메소드가 분리 되어있어. mockk 테스트에서는 `servingTopicRequestToSnsClient()`가 `isSdkHttpResponseHealthy()`결과값을 바로 return 하기 때문에(return 라인에서) verify로 해당 라인이 지나감을 감지하지 못해 "검증이 되지 않는다."

2022-05-21 10:31 UTC, siwony requested changes

2022-05-21 10:31 UTC, siwony commented on src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
> +        }
`isSdkHttpResponseHealthy`메서드에서 `sdkHttpResponse`가 `!isOk`인 상황이 꼭 예외를 발생시켜야 하나요?
클라이언트 입장에서 boolean 형을 리턴하는 메서드는 항상 ture 혹은 false를 리턴하는 것을 기대하는데, true를 리턴하거나 혹은 exception을 발생시키므로 혼선이 있을 거 같네요

`sdkHttpResponse.isSuccessful` 이 항상 true를 리턴한다면 Boolean를 return의미가 없을 거 같다는 의견입니다.

2022-05-21 10:31 UTC, siwony commented on src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
> +        }
><의사결정 주제>
SnsTopicSubSystemFacade/servingTopicRequestToSnsClient() 와 SnsTopicSubSystemFacade/isSdkHttpResponseHealthy() 를 합쳐야 할까 ?
servingTopicRequestToSnsClient() 메소드가 isSdkHttpResponseHealthy() 리턴값에 100% 의존하고 있어 합쳐도 될 것 같다는 생각도 들지만. 나중에 HttpResponse 의 결과 값을 mocking(조작) 하기 위해서는 분리하는것도 좋다는 생각이 든다.

만약 `servingTopicRequestToSnsClient`에서만 해당 코드를 사용한다면 해당 메서드는 합치는게 더 낫다고 생각합니다.

2022-05-21 10:42 UTC, siwony commented on src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
> +class SnsTopicSubSystemFacade {
Facade 패턴를 배우고 있는데  머리속에서 혼선이 생겨 질문드려요

Facade는 주로 서브시스템들(객체)을 레핑하여 서브시스템에 대한 통합된 단순화한 인터페이스를 제공하는데, 
해당 클래스는 서브 시스템들을 레핑하지 않고, 통합된 단순화한 인터페이스를 제공하는게 아닌 단순히 해당 클래스에 있는 method를 이용해 어떠한 로직을 실행한다 생각이 드네요
그래서 저는 해당 클래스가 "Facade"보다 "Service" 가 어울리다고 생각합니다.
이부분에 대해서 어떻게 생각하시나요? 의견이 궁금합니다!

https://sourcemaking.com/design_patterns/facade
facade 패턴에 대해서 해당 글을 참고했어요 특히 Check list 부분을 참고했습니다.
```md
### Check list
1. Identify a simpler, unified interface for the subsystem or component.
2. Design a 'wrapper' class that encapsulates the subsystem.
3. The facade/wrapper captures the complexity and collaborations of the component, and delegates to the appropriate methods.
4. The client uses (is coupled to) the Facade only.
5. Consider whether additional Facades would add value.
```

2022-05-21 10:42 UTC, siwony commented on src/test/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImplTest.kt
> +@SpringBootTest
mocking을 이용한 객체로 `SnsTopicFactoryServiceImpl`를 생성하는데 `@SpringBootTest`를 통해 application context를 로드할 필요가 있나요?

2022-05-21 11:45 UTC, jyeonjyan commented on src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
> +        }
> isSdkHttpResponseHealthy메서드에서 sdkHttpResponse가 !isOk인 상황이 꼭 예외를 발생시켜야 하나요?

네 sdk 에서 발생한 에러에 대해 예외를 발생시켜야 합니다. 
내부적으로 아무런 action도 취하지 않아서요 (이 부분은 향후 변경될 수 있습니다)

2022-05-21 11:46 UTC, jyeonjyan commented on src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
> +        }
> 합치는게 개인적으로 더 낫다고 생각합니다.

지금 보니 `true/false`를 wrapping 하는게 의미가 없는 것 같아서 합쳐서 커밋해보겠습니다.

2022-05-21 11:48 UTC, siwony commented on src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
> +        }
네 확인했습니다~

2022-05-21 11:49 UTC, jyeonjyan commented on src/test/java/site/hirecruit/hr/thirdParty/aws/sns/service/SnsTopicFactoryServiceImplTest.kt
> +@SpringBootTest
아직 프러덕션 코드에 대해 확정된 부분이 없어서 테스트코드는 변경에 열려있습니다.
해당 테스트 클래스의 변경이 닫힐 때 전체 컴퍼넌트 스캔이 필요하지 않다면 그때 제거하겠습니다.

2022-05-21 12:10 UTC, siwony approved these changes

2022-05-22 05:59 UTC, jyeonjyan commented on src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
> +class SnsTopicSubSystemFacade {
좋은 질문 감사드립니다.

저도 GoF 강의와 여러 디자인패턴 레퍼런스를 찾아봤을 때 service-layer와 facade-layer의 경계에 혼란이 있었습니다.
첨부드리는 좋은 토론을 인용해보자면. 항상 디자인 패턴은 관점에서의 차이가 발생한다고 생각합니다.

소프트웨어 공학에서 Facade 라는 의미는 단지 "복잡한 내부 서브 시스템"들을 숨기는 역할로 사용된다고 합니다.
제가 설계한 Facade, `SnsTopicSubSystemFacade` 는 비즈니스 관점에서 알 필요없는 관심사를 분리했다고 생각합니다.

> 서비스는 구성 요소가 실제로 리소스에 액세스하는 방식이고 파사드는 구성 요소를 단순화하는 비트(예: 옵션 구성, 연결 등)입니다.
[stackoverflow 답변을 인용 함](https://stackoverflow.com/a/15079958/18518672)

> 단순히 해당 클래스에 있는 method를 이용해 어떠한 로직을 실행한다 생각이 드네요.

이 부분은 제 Facade 메소드가 Helper 메소드의 역할만을 하는 것 같다고 얘기해주신 것 같습니다.

> 디자인 패턴은 단순히 코드를 구성하는 방법에 대해 이야기하는 방법이며 목적 에 따라 이름이 지정 됩니다. 이것은 아이디어에 '들어 있는' 다른 사람들과 이야기할 때 큰 도움이 됩니다. 전문 용어입니다. 파사드는 애플리케이션에서 라이브러리나 라이브러리 그룹을 숨기는 것이 목적인 도우미 메서드 모음입니다 (건물의 파사드는 뒤에 있는 추한 부분 을 숨깁니다 ). 

제 Facade 는 더 많은 옵션들이 있는 Topic aws-sdk 라이브러리의 구현부(알 필요 없는)를 숨겼다고 생각합니다.
또한 POJO 비즈니스 로직과 외부 라이브러리 혹은 api 영역을 완전히 분리함으로써 결합도는 낮추고 응집도(`service/facade`)는 높혔다고 생각합니다.

> "Facades .. 더 간단한 인터페이스를 제공하고 자체 기능이 없으며 하위 시스템에 대한 액세스를 제한하지 않습니다. ..., 서비스는 대부분 재사용 가능하고 연관되지 않으며 느슨하게 결합된 기능 단위입니다." 요점을 만들었습니다. :)
[stackoverflow 답변을 인용 함](https://stackoverflow.com/a/15084850/18518672)

제 Facade 는 간단한 인터페이스(createTopicRequest..etc)를 제공합니다. 그리고 역할이 분명합니다.


GoF Facade 관점에서 바라봤을때. 그리고 지금 Facade의 용어 사용의 트랜드는 아래의 답변으로 해당 리뷰를 맺겠습니다.
[참고해주세요](https://stackoverflow.com/a/15167936/18518672)

2022-05-22 08:04 UTC, siwony commented on src/main/java/site/hirecruit/hr/thirdParty/aws/sns/service/facade/SnsTopicSubSystemFacade.kt
> +class SnsTopicSubSystemFacade {
명쾌하고 좋은 설명 감사합니다 :)

2022-05-22 08:05 UTC, merged